---
- name: "Override Python Interpeter for CentOS7"
  set_fact:
    ansible_python_interpreter: "/usr/bin/python"
  when:
    - "ansible_distribution == 'CentOS'"
    - "ansible_distribution_major_version | int == 7"

- name: yum update
  yum:
    name: "*"
    state: latest
