---

- hosts: all
  #  remote_user: thanh
  #  become: yes
  #  become_user: root
  #  become_method: sudo

  tasks:
    - name: Set up authorized_keys
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
